name: Build and push strapi image


on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: strapi-task8-siva


jobs:
  build-and-push:
    runs-on: ubuntu-latest


    steps:

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure Aws Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
          | docker login --username AWS --password-stdin \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Create ECR Repository if not exists
        run: |
          aws ecr describe-repositories --repository-names strapi-task8-siva \
          || aws ecr create-repository --repository-name strapi-task8-siva

      - name: Build & Push
        run: |
          IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/strapi-task8-siva:latest
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI
